title: <p align = 'center'>Abhishek Mulay<p>
logo: /assets/img/logo.png
description: I am learning Data Science, AI and Machine Learning
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
